### ISSUE TITLE
Should Base type have a config file in theme-components repo?

### ISSUE THREAD

**Issue by alaczek** [Automattic/components.underscores.me#130]
While looking at #128 I noticed that config array for Base type is hard coded inside generator.php:
https://github.com/Automattic/components.underscores.me/blob/master/inc/components-generator.php#L166, while configs for all other types are over in in https://github.com/Automattic/theme-components/tree/master/configs

This might be confusing for contributors. Should Base type have a standard config json file in theme-components repo?

**Comment by davidakennedy** [comment]
We chatted about this some when we initially worked on the generator at our Vancouver meetup.

@mendezcode and I coded the generator this way because:

* it was easier to build that way.
* it made sense because we don't really want to emphasize the Base as a type.
* we can still change how base works.

We could use a config file if we want to, but I don't see advantage. We just need to explain this difference in the docs.

**Comment by mendezcode** [comment]
Indeed, there is not much advantage having it as a config file together with the types. It may seem as if it doesn't belong really, since the _Base_ type is mostly a _faux_ type, for example:

```
type-base.json
type-blog-classic.json
type-blog-modern.json
type-business.json
type-magazine.json
type-portfolio.json
```

Since all types are for a specific type of theme, base kind of doesn't belong. Currently it is in the actual generator, built-in, which leaves the config files only for real types.

We can leave it as-is and if users complain, we can move it as its own type, but at the moment I believe it can be left as is. Converting it to a real type is very easy too, in case we go that route.

**Comment by davidakennedy** [comment]
Thanks @mendezcode! I like the wait and see approach here. I feel the same way as far as it making more sense in the generator because it's a _faux_ type.
