### ISSUE TITLE
Design Help: Design form placement and form fields for generator

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/components.underscores.me#66]
These would work very similarly to [Underscores.me](http://underscores.me/) for now.

See this [screenshot](https://cloudup.com/cN7BvOABKhG) for the fields we'll include. We need to:

* decide where the forms lives within the current design (preferably having one form that allows you to select which theme type to apply your naming to).
* design form input styles.
* make any adjustments to the existing design/illustrations because a change in height on many containers often breaks the design in some way.

Related: #5 #32

**Comment by karmatosed** [comment]
Why do you have to add the name and also add pick the type in the same section?
Could you perhaps click to use a type and it 'reveals' the form area underneath? It could move the visual and physical focus there and save that long form issue.

**Comment by davidakennedy** [comment]
We could totally do that. I was just stating in the issue that we had to figure that out, really, not advocating doing it a certain way. :smile: 

Maybe in the slider, if the button is clicked for a type, if fires a modal that has the form? That way, the form doesn't have to reside multiple times in each slide. Just an idea. There may be better ways.

**Comment by laurelfulford** [comment]
Modals seem like a good way to work in the form without changing much else. We could anchor it to the same panel somehow, so it blends in - here's a rough version of one idea, but there's probably a lot of cool ways to do this and have it blend in with the theme:

![Print out!](https://cldup.com/RXoy_IosBY-2000x2000.png)

If we wanted to add the form right into the slide with JS, the slides should resize well. The robot is anchored to the bottom - we'll need to make some adjustments, but I don't think it would cause mega breakage.

The conveyor isn't actually part of the slideshow, so adding above there somehow is an option, too, and it could stay in the same spot throughout the slideshow.

**Comment by karmatosed** [comment]
I'd vote strongly against modals in pretty much all use cases. Why can't we have a section under that you just move the page to? Far better than a modal.

**Comment by laurelfulford** [comment]
A section under the slideshow works too :) Just batting around ideas.

**Comment by davidakennedy** [comment]
Modals can work in _some_ cases. I suggested it because I assume we want to also allow users to add their details and change the name of the base theme as well, which is already below the slider.

**Comment by sarahmonster** [comment]
Now might be a good time to consider the overall design of this panel. There are a few issues, this one included, that might benefit from a re-considered structure here, notably:

https://github.com/Automattic/components.underscores.me/issues/20
https://github.com/Automattic/components.underscores.me/issues/39

When we originally worked on the wireframes for this, we had the types listed horizontally, one on top of the other. However, as we were working through the design process, it was suggested that this might make the page scroll too much, particularly if we had lots of types in the future. While I like the conveyor belt concept, the slideshow isn't really as usable as our original concept.

Maybe it's worth brainstorming a re-structuring of this section, with the above issues (and any others as welll?) in mind.

**Comment by laurelfulford** [comment]
I put together some quick ideas. I ended up making them more 'polished' than necessary - I know from experience my sketches are a bit *too* sketchy, and I have to refine them somewhat to make sure the proportions actually work :neutral_face: The vague light blue box represents each type's wireframe/layout.

"Attack of the giant robots" version: https://cloudup.com/i5h99MYMWKx (robots would be cropped on edges on larger screens)
"Vanna White" version: https://cloudup.com/iPcDl1Egzil

In both cases, I think we could 'open' the download form underneath the relevant panel. The form could be statically located in one location, hidden, and cloned/destroyed with JavaScript. We could even preselect type based on where it was opened.

"Bots optional" grid version: https://cloudup.com/ihpV9dUq-ez

I'm less sure about this one, but wanted to include it. I think the form placement could be an issue, unless we want to use the 'Build Theme' button as an anchor, and have it appear below the grid of types. I have a soft spot for the robots so I included them, but I don't think they're necessary, especially if we jazzed up the wireframes/layouts with some colour.

**Comment by ianstewart** [comment]
I'm most fond of the last option. It's more user-need-focused, where the bots are more decorative but the focus is squarely on the theme-type.

**Comment by davidakennedy** [comment]
I also like the last option. The robots are still there, but not the focus. Plus, that layout allows for the text description to lean toward a way users can compare types.

**Comment by karmatosed** [comment]
I think the 2nd option is good. I like the fact that it shows the layout. Perhaps they could be smaller for the layouts so it's 2 column?

I'm not as keen on the grid from a visual appeal point of view. I also think it leads with the layouts which is ok but it could be seen as those being too big and empty.

Perhaps a 2 column version 2 is the happy middle?

**Comment by laurelfulford** [comment]
For comparison's sake, the Vanna-Grid mashup: https://cloudup.com/iQGfJQDbVDc

(@karmatosed, just let me know if that's not quite what you meant!)

**Comment by karmatosed** [comment]
@laurelfulford that's what I was thinking of. Maybe the layout images could be smaller, but I think it loosk better. What do you think?

**Comment by laurelfulford** [comment]
I knocked down the layout images a bit, so the robot-image and text is more of a 50-50 split. It’s a definite improvement, and could possibly even go smaller: https://cloudup.com/iMULiWgDh13

I was originally a fan of the first two mocks, but that’s largely due to my blatant pro-robot agenda :wink: I do agree that a grid-based layout does a better job keeping the focus on the types, and allows easier comparison. I’d be good with either of the grid-like options (or open to other suggestions!).

**Comment by karmatosed** [comment]
+1 for the latest mockup. I think that's a nice balance but also gives the usability benefits. What do others think?

**Comment by davidakennedy** [comment]
I like the latest mockup as well. I do have a few questions though:

* What happens if the text for each description is a different length. It's unlikely they'll all be perfectly the same.
* What happens when you click "Build Theme!" If we have a container slide down with the form elements, is that going to be the full width of the container, or just the column?
* Would we eventually put illustrations of what each type has here?

A few things to think through here, if we haven't started to already.

**Comment by laurelfulford** [comment]
Good questions! I tweaked the mock a bit to go with my answers: https://cloudup.com/i4fnb26IydO

Other thoughts/opinions very welcome!

> What happens if the text for each description is a different length. It's unlikely they'll all be perfectly the same.

For this particular layout, I think we’d keep them lined up, two per row, and the text would just be a bit different in length. We’d probably need to be careful to keep the write ups consistent-ish, but an extra few lines shouldn’t create a big problem. The updated mock now shows the actual text for the types, which does differ in length.

If we expect that the type length could vary a lot, a staggered Masonry layout might work better.

> What happens when you click "Build Theme!" If we have a container slide down with the form elements, is that going to be the full width of the container, or just the column?

This is a good question - having the form ‘slide down’ with this layout could feel awkward. Personally, I think centring the form will look best. If the current type is shown on the form and is editable from there, it seems less important to create a strong visual tie between the form and the type that opened it.

I expected, with the three-column grid layout, that we’d be scrolling down to a form or opening it over top the types. So that’s something else we could look at, too.

What does everyone else think?

> Would we eventually put illustrations of what each type has here?

Yup, I believe the plan was to show the layout in some way.

In the updated mock, I included rough illustrations of each theme (the contrast against the robots needs work!).

We’ll need to figure out what the visual ‘shorthand’ for each type should be. How detailed do we want them to be? How do we make them look different enough from each other? This specific layout has a smallest images for the types - is there enough room to show all we want to show?

**Comment by sixhours** [comment]
Love this version, Laurel. I'd say roll with it. :)

**Comment by ianstewart** [comment]
> Love this version, Laurel. I'd say roll with it. :)

I'll _underscore_ this sentiment.

**Comment by laurelfulford** [comment]
Thanks for all the comments, everyone!

So here's where I got things with the mock: https://cloudup.com/iwuClLdhoXG

All types are present in the grid, including Basic. I included with the others to avoid an odd 'orphan' at the bottom of the two column layout, but it'll be easy enough to pull it out above the rest, too. 

I included an opened form under the assumption that we're going to open the download form under the selected type. Let me know if that works!

It still needs refining, but I'm going start building to get things roughed in, then circle back.

The intro section also needs some love so it fits better, but I'm not exactly sure what to do there. I was thinking we could move the pipe and recycle the conveyor belt idea in some simplified form, but that could be too busy. :confused:

**Comment by davidakennedy** [comment]
Looking good! I will code this so that when you push "Build Theme" on a type, it opens the form, and pre-selects the type you clicked.

Have you given any thought as to how we handle required fields? Right now, type, and theme name are required to download a theme.

Underscores.me handles this in a subtle way by hiding not required options behind a toggle.

Simple solution? We put _(required)_ in the label of the needed form fields.

**Comment by davidakennedy** [comment]
Another note: I'd love to see an iteration where the form labels for the text inputs are visible by default, instead of relying on the placeholder attribute as a label.

Placeholders aren't great as labels because:

* they disappear once a user types in the field.
* they're made to display form field hints.
* they're best used for supplementary information.

I think using them as labels becomes more problematic on longer, multi-field forms.

**Comment by karmatosed** [comment]
@laurelfulford, is the plan still to above the types have a link to download the base?

**Comment by laurelfulford** [comment]
> Have you given any thought as to how we handle required fields? 

When messing with the form fields before, I'd added a simple JavaScript validator, so it wouldn't send the form unless X, Y and Z field had values. It just displayed a message instead. If it makes sense, we could add that as well as the 'required' labels?

> I'd love to see an iteration where the form labels for the text inputs are visible by default, instead of relying on the placeholder attribute as a label.

There's a lot of room - this shouldn't be a problem!

> Is the plan still to above the types have a link to download the base?

I'd included it with the other types but had it first - I'll admit the placement was mostly to avoid having an single type on the last line, since it looked pretty awkward. I will play around with that part a bit more!

**Comment by davidakennedy** [comment]
@laurelfulford:

> When messing with the form fields before, I'd added a simple JavaScript validator, so it wouldn't send the form unless X, Y and Z field had values. It just displayed a message instead. If it makes sense, we could add that as well as the 'required' labels?

Oh, I just meant design-wise. I'll have basic server-side validation in place, and will enhance with JS a bit later.

**Comment by laurelfulford** [comment]
> Oh, I just meant design-wise. 

Oh! Hahah, nevermind then!

I've updated the mock with a) form labels, b) inputs marked with 'required' and c) base actually pulled out and on top for maximum exposure:

https://cloudup.com/ivszdhnY0nc

Couple things I think still need work:

The base section is a bit 'meh'. Plus I'm also not sure what we want to put here for the layout. A header and one column? 

The last type may look better centred than left aligned, so that's something I'll play with.

... plus, any suggestions/recommendations/ideas from y'all! :smile:

**Comment by davidakennedy** [comment]
Solved and merged here:

https://github.com/Automattic/components.underscores.me/commit/7ddd3a597d75f1afd432a213aa3b106ffe1e62ac
