### ISSUE TITLE
SVGs missing from the site

### ISSUE THREAD

**Issue by alaczek** [Automattic/components.underscores.me#81]
Today I noticed that all SVG's are missing from the live components.underscores.me site. 
![components](https://cloud.githubusercontent.com/assets/4550351/12674863/890d7dbc-c686-11e5-90a1-804aee186580.png)
This does not happen locally.

**Comment by sarahmonster** [comment]
I would be willing to bet this is due to `file_get_contents()` being disabled on the server. Can anyone check on this? It was working as expected before, so not sure what's changed since. 

There's a possible workaround using `get_template_part()` if this is the issue, but I'm not a huge fan of that approach, in part because it requires renaming a .svg to .svg.php.

**Comment by mendezcode** [comment]
Actually, `file_get_contents()` seems to be disabled, but only with URLs. Right now, we're using it with URLs to the SVG files, instead of loading the local files.

Using `get_template_directory()` instead of `get_template_directory_uri()` fixes it.

I'll submit a PR in a bit once I get it working ;-)
